### ISSUE TITLE
刷入不了ozip

### ISSUE THREAD

**Issue by lsdlh** [YuxuanZuo/android_device_oppo_sdm660-common#1]
大佬解密完ozip直接rec自动重启了怎么回事

**Comment by YuxuanZuo** [comment]
这是twrp的bug，目前已在3.6.0版本修复。OPPO R11/R11s的twrp近期会被官方接受，届时你可以在官网下载它！

**Comment by lsdlh** [comment]
> 这是twrp的bug，目前已在3.6.0版本修复。OPPO R11/R11s的twrp近期会被官方接受，届时你可以在官网下载它！

官网我看现在没有r11的机型，可以先给我发一份吗，我的邮箱1763221541@qq.com,谢谢
